### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mikaellofgren** [danengh/Python#1]
Hi
Tried to get Patch Automation up and running it did get this error
```
python3 /usr/local/PatchServerAutomation/jamfPatchPolicyUpdater.py 
Traceback (most recent call last):
  File "/usr/local/PatchServerAutomation/jamfPatchPolicyUpdater.py", line 26, in <module>
    from AutomationToolsLib import Logging, AutomationPreferences, SlackNotification
  File "/usr/local/PatchServerAutomation/AutomationToolsLib.py", line 24, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
Solved by download:
`pip3 install requests`

Maybe update the Read me?

**Comment by danengh** [comment]
I will add to the code a try/except block looking to see if this is installed. For now, I have added it to the readme as a required module.

**Comment by mikaellofgren** [comment]
Thanks!

**Comment by danengh** [comment]
Added a try/except block for the requests module.
